spring:
  datasource:
    url: jdbc:mysql://localhost:3336/viajes_rebollo
    username: app_user
    password: app_password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  profiles:
    active: dev
server:
  port: 8080

