services:
  mysql:
    image: mysql:8.0
    container_name: viajes_rebollo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: viajes_rebollo
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3336:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
